@startuml{pfilepuml, Title}(id=TAG1) puml
/'
Atrocious syntax for options for tools with default syntax as follows:
```
startuml{<filename>, <caption>}
```
and after that options can be listed as key-value pairs:
```
startuml{<filename>, <caption>, <option1>=<value1>, ...}
```
but there are some interesting behaviours when title is placed after the '}'
'/
class Object << general >>
Object <|--- ArrayList

note top of Object : In java, every class\nextends this one.

note "This is a floating note" as N1
note "This note is connected\nto several objects." as N2
Object .. N2
N2 .. ArrayList

class Foo
note left: On last defined class

@enduml
