package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"yur4uwe/pac/pkg/tokenizer"
)

type diagram struct {
	name  string
	input string
}

func main() {
	docsDir := flag.String("docs-dir", "docs/class-diagram", "directory with class-diagram markdown docs")
	outPath := flag.String("out", "pkg/tokenizer/examples_generated_testdata.go", "output Go file")
	flag.Parse()

	diagrams, err := collectDiagrams(*docsDir)
	if err != nil {
		fail(err)
	}
	if len(diagrams) == 0 {
		fail(fmt.Errorf("no <plantuml> blocks found under %s", *docsDir))
	}

	content, err := renderGoFile(diagrams)
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(*outPath, []byte(content), 0o644); err != nil {
		fail(err)
	}
}

func collectDiagrams(root string) ([]diagram, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}
	files := make([]string, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if strings.HasSuffix(entry.Name(), ".md") {
			files = append(files, filepath.Join(root, entry.Name()))
		}
	}
	sort.Strings(files)

	var out []diagram
	for _, filePath := range files {
		diagrams, err := extractPlantumlBlocks(filePath)
		if err != nil {
			return nil, err
		}
		out = append(out, diagrams...)
	}
	return out, nil
}

func extractPlantumlBlocks(path string) ([]diagram, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	lines := strings.Split(strings.ReplaceAll(string(data), "\r\n", "\n"), "\n")
	var blocks []diagram
	var buf []string
	inBlock := false
	blockIndex := 0

	for _, line := range lines {
		switch {
		case strings.TrimSpace(line) == "<plantuml>":
			inBlock = true
			buf = buf[:0]
		case strings.TrimSpace(line) == "</plantuml>":
			if inBlock {
				blockIndex++
				name := fmt.Sprintf("%s#%02d", filepath.Base(path), blockIndex)
				blocks = append(blocks, diagram{name: name, input: strings.Join(buf, "\n")})
			}
			inBlock = false
		default:
			if inBlock {
				buf = append(buf, line)
			}
		}
	}

	return blocks, nil
}

func renderGoFile(diagrams []diagram) (string, error) {
	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/docs-examples-gen; DO NOT EDIT.\n")
	sb.WriteString("package tokenizer\n\n")
	sb.WriteString("var docsExamples = []exampleCase{\n")

	for _, d := range diagrams {
		tokens := collectTokens(d.input)
		inputLiteral := formatInputLiteral(d.input)

		sb.WriteString("\t{\n")
		fmt.Fprintf(&sb, "\t\tname: %s,\n", strconv.Quote(d.name))
		fmt.Fprintf(&sb, "\t\tinput: %s,\n", inputLiteral)
		sb.WriteString("\t\texpected: []expectedToken{\n")
		for _, tok := range tokens {
			fmt.Fprintf(&sb, "\t\t\t{typ: %s, literal: %s},\n", tokenTypeName(tok.Type), strconv.Quote(tok.Literal))
		}
		sb.WriteString("\t\t},\n")
		sb.WriteString("\t},\n")
	}

	sb.WriteString("}\n")
	return sb.String(), nil
}

func collectTokens(input string) []tokenizer.Token {
	lex := tokenizer.NewLexer(input)
	out := make([]tokenizer.Token, 0, 64)
	for tok := lex.NextToken(); tok.Type != tokenizer.EOF; tok = lex.NextToken() {
		out = append(out, tok)
	}
	return out
}

func formatInputLiteral(input string) string {
	if strings.Contains(input, "`") {
		return strconv.Quote(input)
	}
	return "`" + input + "`"
}

func tokenTypeName(tt tokenizer.TokenType) string {
	switch tt {
	case tokenizer.ILLEGAL:
		return "ILLEGAL"
	case tokenizer.EOF:
		return "EOF"
	case tokenizer.NEWLINE:
		return "NEWLINE"
	case tokenizer.IDENTIFIER:
		return "IDENTIFIER"
	case tokenizer.STRING:
		return "STRING"
	case tokenizer.NUMBER:
		return "NUMBER"
	case tokenizer.CLASS:
		return "CLASS"
	case tokenizer.ABSTRACT:
		return "ABSTRACT"
	case tokenizer.STRUCT:
		return "STRUCT"
	case tokenizer.INTERFACE:
		return "INTERFACE"
	case tokenizer.ENUM:
		return "ENUM"
	case tokenizer.PACKAGE:
		return "PACKAGE"
	case tokenizer.ANNOTATION:
		return "ANNOTATION"
	case tokenizer.NOTE:
		return "NOTE"
	case tokenizer.STEREOTYPE:
		return "STEREOTYPE"
	case tokenizer.RECORD:
		return "RECORD"
	case tokenizer.DATACLASS:
		return "DATACLASS"
	case tokenizer.EXCEPTION:
		return "EXCEPTION"
	case tokenizer.PROTOCOL:
		return "PROTOCOL"
	case tokenizer.HIDE:
		return "HIDE"
	case tokenizer.SHOW:
		return "SHOW"
	case tokenizer.REMOVE:
		return "REMOVE"
	case tokenizer.RESTORE:
		return "RESTORE"
	case tokenizer.SKINPARAM:
		return "SKINPARAM"
	case tokenizer.SET_PROPERTY:
		return "SET_PROPERTY"
	case tokenizer.TOGETHER:
		return "TOGETHER"
	case tokenizer.END_BLOCK:
		return "END_BLOCK"
	case tokenizer.GENERIC:
		return "GENERIC"
	case tokenizer.NOTE_DIRECTION:
		return "NOTE_DIRECTION"
	case tokenizer.NOTE_POSITION:
		return "NOTE_POSITION"
	case tokenizer.LBRACE:
		return "LBRACE"
	case tokenizer.RBRACE:
		return "RBRACE"
	case tokenizer.LPAREN:
		return "LPAREN"
	case tokenizer.RPAREN:
		return "RPAREN"
	case tokenizer.LBRACKET:
		return "LBRACKET"
	case tokenizer.RBRACKET:
		return "RBRACKET"
	case tokenizer.SEMICOLON:
		return "SEMICOLON"
	case tokenizer.COLON:
		return "COLON"
	case tokenizer.COMMA:
		return "COMMA"
	case tokenizer.VISIBILITY:
		return "VISIBILITY"
	case tokenizer.MODIFIER:
		return "MODIFIER"
	case tokenizer.RELATIONSHIP:
		return "RELATIONSHIP"
	case tokenizer.COMMENT:
		return "COMMENT"
	case tokenizer.SEPARATOR:
		return "SEPARATOR"
	case tokenizer.ALIAS:
		return "ALIAS"
	case tokenizer.START:
		return "START"
	case tokenizer.END:
		return "END"
	case tokenizer.PREPROCESSOR:
		return "PREPROCESSOR"
	default:
		return "UNKNOWN"
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
