package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	out, err := exec.Command("go", "list", "std").Output()
	if err != nil {
		log.Fatalf("failed to run 'go list std': %v", err)
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var packages []string

	for _, line := range lines {
		pkgPath := strings.TrimSpace(line)
		if pkgPath == "" ||
			strings.HasPrefix(pkgPath, "internal/") ||
			strings.Contains(pkgPath, "/internal/") ||
			strings.HasPrefix(pkgPath, "vendor/") ||
			strings.Contains(pkgPath, "/vendor/") ||
			strings.HasPrefix(pkgPath, "cmd/") {
			continue
		}
		packages = append(packages, pkgPath)
	}

	sort.Strings(packages)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen.go; DO NOT EDIT.\n\n")
	buf.WriteString("package stdlib\n\n")
	buf.WriteString("var stdlibPackageList = []string{\n")
	for _, pkg := range packages {
		fmt.Fprintf(&buf, "\t%q,\n", pkg)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated code: %v", err)
	}

	targetFile := "packages_gen.go"
	if err := os.WriteFile(targetFile, formatted, 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", targetFile, err)
	}
	fmt.Printf("Successfully generated %s with %d stdlib packages\n", targetFile, len(packages))
}
