@startuml
interface Greeter {
  +Greet(name string) string
}

class User {
  +name string
  +Greet(name string) string
}
User ..|> Greeter

enum Status {
  +Inactive
  -- Non-default values --
  +Active
}
@enduml
